### ISSUE TITLE
Crashes while using --job (GC3Pie/2.4.2 + Slurm)

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-framework#2204]
Hi all,

Everytime i try to install software with the --job option i get this message after few minutes:

`== temporary log file in case of crash /tmp/eb-DqqWHV/easybuild-uUo01C.log
== resolving dependencies ...
== GC3Pie job overview: 3 submitted (total: 7)
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/Easybuild/software/EasyBuild/3.1.2/lib/python2.6/site-packages/easybuild_framework-3.1.2-py2.6.egg/easybuild/main.py", line 453, in <module>
    main()
  File "/Easybuild/software/EasyBuild/3.1.2/lib/python2.6/site-packages/easybuild_framework-3.1.2-py2.6.egg/easybuild/main.py", line 413, in main
    submit_jobs(ordered_ecs, eb_go.generate_cmd_line(), testing=testing)
  File "/Easybuild/software/EasyBuild/3.1.2/lib/python2.6/site-packages/easybuild_framework-3.1.2-py2.6.egg/easybuild/tools/parallelbuild.py", line 144, in submit_jobs
    return build_easyconfigs_in_parallel(command, ordered_ecs, prepare_first=prepare_first)
  File "/Easybuild/software/EasyBuild/3.1.2/lib/python2.6/site-packages/easybuild_framework-3.1.2-py2.6.egg/easybuild/tools/parallelbuild.py", line 115, in build_easyconfigs_in_parallel
    active_job_backend.complete()
  File "/Easybuild/software/EasyBuild/3.1.2/lib/python2.6/site-packages/easybuild_framework-3.1.2-py2.6.egg/easybuild/tools/job/gc3pie.py", line 239, in complete
    self._engine.progress()
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 1305, in progress
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 416, in update_job_state
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 452, in __update_application
IndexError: string index out of range
`

At log file i can see the same error as above, and i do not know if some software was installed successfully or not.

Doe's anyone know what cause that error? 

Thanks,
Igor

**Comment by boegel** [comment]
We'll need some more details I guess...

Which version of GC3Pie are you using, and which configuration?

cc @riccardomurri

**Comment by nortex** [comment]
Hi, i am using GC3Pie v.2.4.2 with default configuration:

`[resource/slurm]
enabled = yes
type = slurm

# use settings below when running GC3Pie on the cluster front-end node
frontend = localhost
transport = local
auth = none

max_walltime = 2 days
# max # jobs ~= max_cores / max_cores_per_job
max_cores_per_job = 16
max_cores = 1024
max_memory_per_core = 2 GiB
architecture = x86_64

# to add non-std options or use SLURM tools located outside of
# the default PATH, use the following:
#sbatch = /usr/bin/sbatch --mail-type=ALL`

**Comment by riccardomurri** [comment]
@nortex Are you able to reproduce the issue while running at DEBUG log level and post the log? (here or on a paste bin)

**Comment by nortex** [comment]
Hi,

Logically i found what causing that error, this is happen always when some application didn't install successfully(because of lack of some OS dependency or broken source link for example). The question is whether the error is what i should get? or should i get a normal log and message that some software was not installed successfully with the name and reason so i would not have to manually enter to compute nodes and searching for the log files?

The debug log is too long, here are the lines before the crash:

`== 2017-05-09 07:54:25,206 batch.py:385 INFO Creating remote temporary folder: command 'mkdir -p $HOME/.gc3pie_jobs; mktemp -d $HOME/.gc3pie_jobs/lrms_job.XXXXXXXXXX' 
== 2017-05-09 07:54:25,222 transport.py:943 DEBUG Executed local command 'mkdir -p $HOME/.gc3pie_jobs; mktemp -d $HOME/.gc3pie_jobs/lrms_job.XXXXXXXXXX', got exit status: 0
== 2017-05-09 07:54:25,223 batch.py:330 DEBUG prologue script not defined for resource slurm
== 2017-05-09 07:54:25,223 batch.py:330 DEBUG generic_prologue script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG prologue_content script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG generic_prologue_content script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG epilogue script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG generic_epilogue script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG epilogue_content script not defined for resource slurm
== 2017-05-09 07:54:25,224 batch.py:330 DEBUG generic_epilogue_content script not defined for resource slurm
== 2017-05-09 07:54:25,248 transport.py:943 DEBUG Executed local command '/bin/sh -c 'cd $HOME/.gc3pie_jobs/lrms_job.AIqORVTNMt && '\''sbatch'\'' '\''--no-requeue'\'' '\''--time'\'' '\''1440'\'' '\''--output'\'' '\''eb-Perl-5.20.3-foss-2015b-gc3pie-job-20175409-UTC-04-54-25.log'\'' '\''--job-name'\'' '\''Perl-5.20.3-foss-2015b'\'' ./script.9edbd747-37c4-46d6-a858-59d5f61f761d.sh'', got exit status: 0
== 2017-05-09 07:54:25,248 batch.py:485 DEBUG Job submitted with jobid: 1455631
== 2017-05-09 07:54:25,248 core.py:368 INFO Successfully submitted Application@2876dd0 to: slurm
== 2017-05-09 07:54:25,249 __init__.py:1811 DEBUG Calling state-transition handler 'submitted' on Application@2876dd0 ...
== 2017-05-09 07:54:25,249 core.py:87 DEBUG Performing matching of resource(s) slurm to task '<gc3libs.workflow.ParallelTaskCollection object at 0x2b48fd0>' ...
== 2017-05-09 07:54:25,249 __init__.py:1811 DEBUG Calling state-transition handler 'submitted' on <gc3libs.workflow.ParallelTaskCollection object at 0x2b48fd0> ...
== 2017-05-09 07:54:25,249 core.py:1671 DEBUG Engine.stats: Restricting to object of class 'Application'
== 2017-05-09 07:54:25,249 build_log.py:216 INFO GC3Pie job overview: 1 submitted (total: 1)
== 2017-05-09 07:54:55,280 workflow.py:422 DEBUG Task #0 in state SUBMITTED
== 2017-05-09 07:54:55,280 __init__.py:1811 DEBUG Calling state-transition handler 'submitted' on <gc3libs.workflow.DependentTaskCollection object at 0x2876b50> ...
== 2017-05-09 07:54:55,280 core.py:435 DEBUG About to update state of application: Application@2876dd0 (currently: SUBMITTED)
== 2017-05-09 07:54:55,280 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-09 07:54:55,280 transport.py:893 DEBUG Opening LocalTransport... 
== 2017-05-09 07:54:55,281 batch.py:567 DEBUG Checking remote job status with 'squeue --noheader -o %i^%T^%r -j 1455631' ...
== 2017-05-09 07:54:55,302 transport.py:943 DEBUG Executed local command 'squeue --noheader -o %i^%T^%r -j 1455631', got exit status: 0
== 2017-05-09 07:54:55,302 slurm.py:232 DEBUG translating SLURM's state 'RUNNING' to gc3libs.Run.State
== 2017-05-09 07:54:55,302 __init__.py:1811 DEBUG Calling state-transition handler 'running' on Application@2876dd0 ...
== 2017-05-09 07:54:55,302 __init__.py:1811 DEBUG Calling state-transition handler 'running' on <gc3libs.workflow.ParallelTaskCollection object at 0x2b48fd0> ...
== 2017-05-09 07:54:55,303 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-09 07:54:55,303 transport.py:893 DEBUG Opening LocalTransport... 
== 2017-05-09 07:54:55,303 slurm.py:487 DEBUG Running `squeue --noheader -o '%i^%T^%u^%U^%r^%R'`...
== 2017-05-09 07:54:55,324 transport.py:943 DEBUG Executed local command 'squeue --noheader -o '%i^%T^%u^%U^%r^%R'', got exit status: 0
== 2017-05-09 07:54:55,324 slurm.py:496 DEBUG Computing updated values for total/available slots ...
== 2017-05-09 07:54:55,324 slurm.py:514 INFO Updated resource 'slurm' status: free slots: -1, total running: 104, own running jobs: 1, own queued jobs: 0, total queued jobs: 0
== 2017-05-09 07:54:55,325 core.py:1671 DEBUG Engine.stats: Restricting to object of class 'Application'
== 2017-05-09 07:54:55,325 build_log.py:216 INFO GC3Pie job overview: 1 running (total: 1)
== 2017-05-09 07:55:25,355 workflow.py:422 DEBUG Task #0 in state RUNNING
== 2017-05-09 07:55:25,355 __init__.py:1811 DEBUG Calling state-transition handler 'running' on <gc3libs.workflow.DependentTaskCollection object at 0x2876b50> ...
== 2017-05-09 07:55:25,356 core.py:435 DEBUG About to update state of application: Application@2876dd0 (currently: RUNNING)
== 2017-05-09 07:55:25,356 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-09 07:55:25,356 transport.py:893 DEBUG Opening LocalTransport... 
== 2017-05-09 07:55:25,356 batch.py:567 DEBUG Checking remote job status with 'squeue --noheader -o %i^%T^%r -j 1455631' ...
== 2017-05-09 07:55:25,377 transport.py:943 DEBUG Executed local command 'squeue --noheader -o %i^%T^%r -j 1455631', got exit status: 0
== 2017-05-09 07:55:25,378 slurm.py:232 DEBUG translating SLURM's state 'RUNNING' to gc3libs.Run.State
== 2017-05-09 07:55:25,378 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-09 07:55:25,378 transport.py:893 DEBUG Opening LocalTransport... 
== 2017-05-09 07:55:25,378 slurm.py:487 DEBUG Running `squeue --noheader -o '%i^%T^%u^%U^%r^%R'`...
== 2017-05-09 07:55:25,400 transport.py:943 DEBUG Executed local command 'squeue --noheader -o '%i^%T^%u^%U^%r^%R'', got exit status: 0
== 2017-05-09 07:55:25,400 slurm.py:496 DEBUG Computing updated values for total/available slots ...
== 2017-05-09 07:55:25,400 slurm.py:514 INFO Updated resource 'slurm' status: free slots: -1, total running: 104, own running jobs: 1, own queued jobs: 0, total queued jobs: 0
== 2017-05-09 07:55:25,400 core.py:1671 DEBUG Engine.stats: Restricting to object of class 'Application'
== 2017-05-09 07:55:25,400 build_log.py:216 INFO GC3Pie job overview: 1 running (total: 1)
== 2017-05-09 07:55:55,431 workflow.py:422 DEBUG Task #0 in state RUNNING
== 2017-05-09 07:55:55,431 core.py:435 DEBUG About to update state of application: Application@2876dd0 (currently: RUNNING)
== 2017-05-09 07:55:55,431 __init__.py:169 DEBUG Checking auth: NoneAuth (always successful).
== 2017-05-09 07:55:55,431 transport.py:893 DEBUG Opening LocalTransport... 
== 2017-05-09 07:55:55,432 batch.py:567 DEBUG Checking remote job status with 'squeue --noheader -o %i^%T^%r -j 1455631' ...
== 2017-05-09 07:55:55,457 transport.py:943 DEBUG Executed local command 'squeue --noheader -o %i^%T^%r -j 1455631', got exit status: 0
== 2017-05-09 07:55:55,457 __init__.py:1811 DEBUG Calling state-transition handler 'terminating' on Application@2876dd0 ...
== 2017-05-09 07:55:55,457 batch.py:603 DEBUG Retrieving accounting information using command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 1455631' ...
== 2017-05-09 07:55:55,559 transport.py:943 DEBUG Executed local command 'env SLURM_TIME_FORMAT=standard sacct --noheader --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 1455631', got exit status: 0
== 2017-05-09 07:55:55,572 build_log.py:147 ERROR EasyBuild crashed with an error (at ?:651 in update_job_state): Error in querying Batch resource 'slurm': IndexError: string index out of range
== 2017-05-09 07:55:55,573 core.py:447 DEBUG Error getting status of application 'Application@2876dd0': IndexError: string index out of range
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gc3libs/core.py", line 443, in __update_application
    state = lrms.update_job_state(app)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/__init__.py", line 166, in wrapper
    return fn(self, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/batch.py", line 605, in update_job_state
    return self.__do_acct(job, cmd, self._parse_acct_output)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/batch.py", line 530, in __do_acct
    jobstatus = parse(stdout)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/slurm.py", line 383, in _parse_acct_output
    vmem = SlurmLrms._parse_memspec(maxvmsize)
  File "build/bdist.linux-x86_64/egg/gc3libs/backends/slurm.py", line 425, in _parse_memspec
    unit = m[-1]
IndexError: string index out of range`

**Comment by riccardomurri** [comment]
Thanks for posting the log, it is very useful!

Can you please run the following command and post its output?

    env SLURM_TIME_FORMAT=standard sacct --parsable --format jobid,exitcode,state,ncpus,elapsed,totalcpu,submit,start,end,maxrss,maxvmsize -j 1455631

**Comment by nortex** [comment]
Output:

`JobID|ExitCode|State|NCPUS|Elapsed|TotalCPU|Submit|Start|End|MaxRSS|MaxVMSize|
1455631|1:0|FAILED|1|00:01:06|00:00:00|2017-05-09T07:54:25|2017-05-09T07:54:25|2017-05-09T07:55:31|||
1455631.batch|1:0|FAILED||00:01:06|00:00:00|2017-05-09T07:54:25|2017-05-09T07:54:25|2017-05-09T07:55:31|||`

**Comment by riccardomurri** [comment]
I think this has already been fixed in the "master" branch of GC3Pie (to be released as 2.5.0 some day).
Would you be able to test it?

Unfortunately, it requires some little changes to EB code, namely merging (at least) the first hunk of the patch at #2211 

Updating GC3Pie code should be more mechanical: just `git clone` the masterbranch and then `pip install -e .` into the virtualenv you use for running EB.

**Comment by nortex** [comment]
Hi,

I still do not see the 2.5.0 version available neither on EasyBuild repository or on github...

Is there still no way to fix the errors i keep receiving?

**Comment by riccardomurri** [comment]
hi @nortex 

GC3Pie 2.5.0 has not yet been released -- at the moment is really refers to code in the "master" branch on GitHub.
Update instructions are in my previous comment, but please point out if they are not sufficient or clear.

Ciao,
R

**Comment by nortex** [comment]
I didn't understand what file i need to edit, and where this file is located

**Comment by riccardomurri** [comment]
You have to: 

* apply the patch in [PR #2211](https://github.com/easybuilders/easybuild-framework/pull/2211/files) to file `easybuild/tools/job/gc3pie.py` (part of Easybuild Framework)
* install GC3Pie "master" (i.e., 2.5.0.dev) instead of GC3Pie 2.4.2 which comes with EB; GC3Pie should be installed within the same virtualenv where the EB code resides.  A simple way to do it would be to run::

    pip install git+https://github.com/tissuemaps/gc3pie@master

**Comment by nortex** [comment]
Hi,

I followed your steps, changed the easybuild gc3pie.py file and executed the pip install git command on my installed GC3Pie python site-packages.

Now i receive the next error:

== resolving dependencies ...
ERROR: Failed to create GC3Pie engine: Could not instanciate resource type 'slurm': ImportError: No module named cryptography.hazmat.backends

**Comment by riccardomurri** [comment]
Can you please save the following to a file `gc3pie-reqs.txt` and then run `pip install -r gc3pie-reqs.txt` ?  (Again from within the EB virtualenv)

```
asn1crypto==0.23.0
bcrypt==3.1.3
cffi==1.11.0
coloredlogs==7.3
cryptography==2.0.3
dictproxyhack==1.1
docutils==0.14
enum34==1.1.6
future==0.16.0
humanfriendly==4.4.1
idna==2.6
ipaddress==1.0.18
lockfile==0.12.2
monotonic==1.3
paramiko==2.3.1
parsedatetime==2.4
prettytable==0.7.2
pyasn1==0.3.6
pyCLI==2.0.3
pycparser==2.18
pycrypto==2.6.1
PyNaCl==1.1.2
python-daemon==2.1.2
PyYAML==3.12
six==1.11.0
SQLAlchemy==1.1.14
wheel==0.24.0
```

This should solve any dependency problem.

**Comment by nortex** [comment]
Hi this gives me a problem with libffi package:

`Collecting PyNaCl==1.1.2 (from -r gc3pie-reqs.txt (line 22))
  Using cached PyNaCl-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'`

Those the new version using PyNaCI + libffi? when i was installing with eb GC3Pie version 2.4.2 i didn't had any problems with missing libffi library.

**Comment by riccardomurri** [comment]
> new version using PyNaCI + libffi? when i was installing with eb GC3Pie version 2.4.2 i didn't had any problems with missing libffi library.

*PyNaCl* is a dependency of *paramiko*, which GC3Pie uses to SSH into target hosts.  At the time of the 2.4.2 release, *paramiko* did not have that dependency...

Anyway, you can fix it easily by running::

    # on Debian/Ubuntu
    sudo apt-get install libffi-dev libssl-dev

    # on CentOS/RHEL
    sudo yum install libffi-devel openssl-devel

or maybe there are already EB recipes for building them.

**Comment by nortex** [comment]
Hi,

I see there is still no release of newer GC3Pie, can you explain or instruct me how can i make sure that i did all the steps above from within the EB virtualenv?  What i did i just loaded the EasyBuild module and did all the steps above.

**Comment by riccardomurri** [comment]
GC3Pie 2.5.0 was just released, hopefully @boegel will have time to make the upcoming release of EB use it.

**Comment by boegel** [comment]
Two PRs relevant to GC3Pie 2.5.0 (just released) were merged into the `develop` branch here just now: #2474 + #2554.

These will be included in the upcoming EasyBuild v3.7.0 release, together with an easyconfig file to GC3Pie 2.5.0 (pending, see https://github.com/easybuilders/easybuild-easyconfigs/pull/6791).
